#! /bin/sh
#
# /init executable file in the initramfs
#
mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

ip link set up dev lo

ifconfig eth0 172.29.0.2 netmask 255.255.0.0 up

/agent

reboot