#! /bin/sh
#
# /init executable file in the initramfs
#
mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

ip link set up dev lo

export CARGO_HOME='/usr/local/cargo'
export RUSTUP_HOME='/usr/local/rustup'
export RUST_VERSION='1.77.2'

export PATH=$CARGO_HOME/bin:$PATH

ln -s /proc/net/pnp /etc/resolv.conf

/agent

reboot